### PR TITLE
Commented out the sidebar and its hamburger button

### PR DESCRIPTION
**Pull request by ghost**
As mentioned in #45

### CODE REVIEW

**Review by 2bndy5 — DISMISSED** [review]

**Comment by 2bndy5** [comment]
Something was wrong here. Looking closer, there was an older commented out section of HTML that threw off the the new comment block
image
this is what I got when I loaded your fork. btw could you work in a branch of our repo? to test this I had to clone your fork and setup the debugger in VSCode. If it was a branch of our repo, then I wouldn't have to clone your fork just to test it.

**Comment by 2bndy5** [comment]
Sent your github account an invite... Not sure if that's why you started another fork. Accept the invite, then use branches

**Comment by ghost** [comment]
As far as I know, making a fork is the only way to create a pull request.

Have you already resolved this issue with the commits above or would you like me to take a look / work on it?

**Comment by 2bndy5** [comment]
You can make pull request from other branches as well. Are you a student at DVC? The fact that you are asking if this works tells me you never tested it. Testing someone else's fork is the real problem here. I already have a repo folder named webapp. If I have to clone your fork to test it, I have to create a separate folder and a new VSCode debugger. To be honest, you shouldn't create pull requests until you know what you have is working & stable. We won't be using a CI to do this for you.

**Comment by ghost** [comment]
Oh I see, I must've misunderstood you. This repository doesn't have any contribution guidelines so I wasn't aware that that's the way you wanted to have things done.

And yes, I did not test it. I commented out the exact lines specified in the issue. The task was so simple that I couldn't even imagine messing it up. I apologize for the inconvenience :smile:

**Comment by 2bndy5** [comment]
It's all good we're working up some guidelines to avoid this in the future.

**Pull request merged**
